version: '3'

name: 'media'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - $CONFIGDIR/jellyfin/config:/config
      - $DATADIR/movies:/movies
      - $DATADIR/shows:/shows
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    devices:
      - /dev/dri:/dev/dri

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - $CONFIGDIR/qbittorrent/config:/config
      - $DATADIR/downloads:/downloads
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    ports:
      - 7878:7878
    volumes:
      - $CONFIGDIR/radarr/config:/config
      - $DATADIR/downloads:/downloads
      - $DATADIR/movies:/movies
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    ports:
      - 8989:8989
    volumes:
      - $CONFIGDIR/sonarr/config:/config
      - $DATADIR/downloads:/downloads
      - $DATADIR/shows:/shows
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    ports:
      - 6767:6767
    volumes:
      - $CONFIGDIR/bazarr/config:/config
      - $DATADIR/movies:/movies
      - $DATADIR/shows:/shows
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    ports:
      - 8191:8191
    volumes:
      - $CONFIGDIR/flaresolverr/config:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    depends_on:
      - flaresolverr
    ports:
      - 9696:9696
    volumes:
      - $CONFIGDIR/prowlarr/config:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ

  # jackett:
  #   image: ghcr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   restart: unless-stopped
  #   ports:
  #     - 9117:9117
  #   volumes:
  #     - /home/gustavo/mediaserver/jackett/config:/config
  #     - /home/gustavo/mediaserver/jackett/downloads:/downloads
  #   environment:
  #     - TZ=America/Sao_Paulo
  #     - PUID=1000
  #     - PGID=1000
  #     - AUTO_UPDATE=true

